# Generated by Django 4.2.1 on 2023-11-28 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
